#:schema node_modules/wrangler/config-schema.json
name = "bento-cname"
main = "src/index.ts"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]


[vars]
BENTO_USERNAME = 'lalaloop'
